export const EXAMPLE_PATH = 'Lunect Holdings'
export const CMS_NAME = 'Lunect Holdings'
// export const HOME_OG_IMAGE_URL =
//   'https://og-image.vercel.app/Next.js%20Blog%20Starter%20Example.png?theme=light&md=1&fontSize=100px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-black-logo.svg'
export const BLOG_NAME = 'Lunect Holdings'
export const KEYWORDS = 'Tommy Daniel, blog, self funded search'
export const DESCRIPTION = 'Lunect Holdings Searcher'
export const AUTHOR = 'Tommy Daniel'
export const LANG = 'en-CA'
export const GITHUB_REPO = 'https://github.com/tdronin'
